import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const base=import.meta.env.VITE_TROOP_API||'';
async function call(path:string,token:string,init:RequestInit={}){const r=await fetch(base+path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const j=await r.json();if(!r.ok)throw Error(j.error||String(r.status));return j}
type Tab='Overview'|'Marketplace'|'Simulation'|'Appeals'|'Mission'|'Usage';
function App(){const[token,setToken]=useState(sessionStorage.troopToken||'');const[tab,setTab]=useState<Tab>('Overview');const[data,setData]=useState<any>(null);const[error,setError]=useState('');const[mission,setMission]=useState('');const[skill,setSkill]=useState('');
const run=async(fn:()=>Promise<any>)=>{setError('');try{setData(await fn())}catch(e){setError(String(e))}};useEffect(()=>{sessionStorage.troopToken=token},[token]);
const actions:Record<Tab,()=>void>={Overview:()=>run(()=>Promise.all([call('/readyz',token),call('/v1/marketplace/agents',token),call('/v1/appeals?pending=true',token)]).then(([health,agents,appeals])=>({health,agents:agents.count,pending_appeals:appeals.count}))),Marketplace:()=>run(()=>call('/v1/marketplace/agents?skill='+encodeURIComponent(skill),token)),Simulation:()=>run(()=>call('/v1/simulations/run',token,{method:'POST',body:JSON.stringify({scenario:'chaos',seed:42,tasks:1000,agents:12,failure_rate:.05,chaos_rate:.1})})),Appeals:()=>run(()=>call('/v1/appeals?pending=true',token)),Mission:()=>run(()=>call('/v1/missions/'+encodeURIComponent(mission),token)),Usage:()=>run(()=>call('/v1/missions/'+encodeURIComponent(mission)+'/usage',token))};
return <><header><b>Agent Troop</b><span>M10 Product Console</span><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Bearer token"/></header><main><nav>{(Object.keys(actions)as Tab[]).map(x=><button key={x} className={tab===x?'on':''} onClick={()=>{setTab(x);setData(null)}}>{x}</button>)}</nav><section><h1>{tab}</h1>{tab==='Marketplace'&&<input value={skill} onChange={e=>setSkill(e.target.value)} placeholder="Skill filter"/>}{(tab==='Mission'||tab==='Usage')&&<input value={mission} onChange={e=>setMission(e.target.value)} placeholder="Mission ID"/>}<button className="primary" onClick={actions[tab]}>{tab==='Simulation'?'Run deterministic chaos':'Refresh'}</button>{error&&<p className="error">{error}</p>}<pre>{data?JSON.stringify(data,null,2):'Select an action to load live control-plane data.'}</pre></section></main></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
